service: app-ts-interaction
frameworkVersion: '3.38.0'

useDotenv: true

params: ${file(./environment/params.yml)}
provider: ${file(./environment/provider.yml)}

plugins:
    - serverless-plugin-typescript
    - serverless-offline

custom:
  serverless-offline:
    httpPort: 3000
    noPrependStageInUrl: true
    noTimeout: true

package:
    individually: true
    exclude:
        - '.*/**'
        - 'node_modules'

functions:
  comments-getall:
    handler: cmd/comment/get.handler
    events:
      - http:
          path: /comments
          method: get
  comments-store:
    handler: cmd/comment/store.handler
    events:
      - http:
          path: /comments
          method: post
