name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    uses: ncostamagna/github-workflows-templates/.github/workflows/node-serverless-deploy.yml@feat/deploy-node
    permissions:
      id-token: write
      contents: write
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}